// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"daily-practise/greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: GreetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/from/create",
				Handler: CreateHandler(serverCtx),
			},
		},
	)
}
